cmake_minimum_required(VERSION 3.10)

project(Corte2Entrega3 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_subdirectory(leetcode_1797_auth_manager)
add_subdirectory(leetcode_3709_exam_tracker)
add_subdirectory(exercism_crypto_square)
add_subdirectory(exercism_bank_account)
